{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oidc-forward-auth-middleware.serviceAccountName" . }}
  labels:
    {{- include "oidc-forward-auth-middleware.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oidc-forward-auth-middleware.fullname" . }}
rules:
- apiGroups: [ "" ]
  resources: [ secrets ]
  verbs: [ get ]
- apiGroups: [ networking.k8s.io ]
  resources: [ ingresses ]
  verbs: [ get, list, watch ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oidc-forward-auth-middleware.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "oidc-forward-auth-middleware.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "oidc-forward-auth-middleware.fullname" . }}

{{- end }}
