name: test helm build

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Helm Chart
        run: |
          if [[ $GITHUB_REF_NAME != v* ]]; then
            exit 0
          fi
          mkdir -p .helm-packages
          HELM_VERSION="${GITHUB_REF_NAME#v}"
          helm package ./helm --version "$HELM_VERSION" --app-version "$GITHUB_REF_NAME" -d .helm-packages
          for pkg in .helm-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/${{ github.repository_owner }}/helm-charts
          done
